set (YOSYS_CONFIG ${YOSYS_PREFIX}/bin/yosys-config)
message(STATUS "YOSYS_CONFIG: ${YOSYS_CONFIG}")
function(check_yosys_config_result result)
        if (NOT (0 EQUAL result))
                message (FATAL_ERROR "execute yosys-config failed")
        endif()
endfunction()
execute_process(COMMAND ${YOSYS_CONFIG} --cxx OUTPUT_VARIABLE YOSYS_CXX RESULT_VARIABLE YOSYS_CONFIG_RESULT)
check_yosys_config_result(${YOSYS_CONFIG_RESULT})
string(STRIP ${YOSYS_CXX} YOSYS_CXX)
execute_process(COMMAND ${YOSYS_CONFIG} --cxxflags OUTPUT_VARIABLE YOSYS_CXX_FLAGS RESULT_VARIABLE YOSYS_CONFIG_RESULT)
check_yosys_config_result(${YOSYS_CONFIG_RESULT})
string(STRIP ${YOSYS_CXX_FLAGS} YOSYS_CXX_FLAGS)
execute_process(COMMAND ${YOSYS_CONFIG} --ldflags OUTPUT_VARIABLE YOSYS_LD_FLAGS RESULT_VARIABLE YOSYS_CONFIG_RESULT)
check_yosys_config_result(${YOSYS_CONFIG_RESULT})
string(STRIP ${YOSYS_LD_FLAGS} YOSYS_LD_FLAGS)
execute_process(COMMAND ${YOSYS_CONFIG} --ldlibs OUTPUT_VARIABLE YOSYS_LD_LIBS RESULT_VARIABLE YOSYS_CONFIG_RESULT)
check_yosys_config_result(${YOSYS_CONFIG_RESULT})
string(STRIP ${YOSYS_LD_LIBS} YOSYS_LD_LIBS)

if (NOT ((YOSYS_CXX STREQUAL gcc) OR (YOSYS_CXX STREQUAL clang)))
        message (FATAL_ERROR "only build with gcc or clang is supported for slang-yosys")
endif()

string(REGEX MATCH "-std=[^ ]*" YOSYS_CXX_STANDARD ${YOSYS_CXX_FLAGS})
if (NOT (YOSYS_CXX_STANDARD STREQUAL "-std=c++17" OR YOSYS_CXX_STANDARD STREQUAL "-std=c++20"))
        message (FATAL_ERROR "yosys should be compiled with -std=c++17 or -std=c++20, while it is compiled with ${YOSYS_CXX_STANDARD}")
endif()

string(REGEX REPLACE "-std=[^ ]*" "" YOSYS_CXX_FLAGS ${YOSYS_CXX_FLAGS})

set (CMAKE_CXX_FLAGS "${YOSYS_CXX_FLAGS} ${CMAKE_CXX_FLAGS}")
function (target_link_with_yosys target)
        target_link_libraries(${target} PRIVATE ${YOSYS_LD_FLAGS} ${YOSYS_LD_LIBS} yosys)
endfunction()
